### ISSUE TITLE
Question about training time.

### ISSUE THREAD

**Issue by icecream-Tnak** [amazon-research/semimtr-text-recognition#1]
Very Nice Work! I noticed in your implementation details, ST used for training, 25 epochs with 304 batchsize. I would like to ask

1) Is the batchsize here the total batch size on 4 GPU, which means the batch size on each V100 is 76.

2) How long does it take to train an epoch?

I have also tried to train ABINet. However, each epoch seemed to take a very long training time.

**Comment by aaberdam** [comment]
Hi,

1. Right, the batch size is the total batch size.
 
2. The training time of a single epoch depends on the size of the training datasets. SemiMTR trains on Real-L (276K) and Real-U (4.2M), while ABINet originally trained on the synthetic datasets (16M).
Quoting from an updated version of our paper that will be released soon:

> Our method uses the architecture of ABINet and therefore shares the same inference time. 
A comparison with the number of iterations of ABINet training shows that our vision model pretraining is longer by 65% (495K vs.~300K iterations), but our fusion model training is shorter by 65% (130K vs.~376K).
On 4 NVIDIA 1080Ti GPUs, each iteration of our vision pretraining and fine-tuning takes 0.77s and 1.45s correspondingly, whereas ABINet's iteration takes 0.51s and 0.91s.
Combining these outcomes results in an overall increase of 15% in training time compared to ABINet.
