### ISSUE TITLE
NaN in input tensor 

### ISSUE THREAD

**Issue by dikubab** [amazon-research/semimtr-text-recognition#4]
The language model gives NaN or Inf found in input tensor.
[train.txt](https://github.com/amazon-research/semimtr-text-recognition/files/9691951/train.txt)
 Can help why it is failing to train on non English character?

**Comment by aaberdam** [comment]
Hi,

Thank you for the interest in our work.
Please refer in this [issue](https://github.com/amazon-research/semimtr-text-recognition/issues/3#issuecomment-1260550524), to the changes that are required for training on non-English language.
In particular, make sure that you created `AmharicText_train.csv` and `AmharicText_eval.csv` with the right character set.

Let me know if it works for you.
Aviad

**Comment by dikubab** [comment]
Thank you for your prompt response. As per your suggestion, I have cleaned my train and valid text datasets and now it is working for me. You can close the issue.
